### PR TITLE
*: cut v0.9.0 release

### PR DESCRIPTION
**Pull request by s-urbaniak**
cc @brancz @simonpasquier @paulfantom 

Signed-off-by: Sergiusz Urbaniak <sergiusz.urbaniak@gmail.com>

### CODE REVIEW

**Comment by s-urbaniak** [comment]
urgs, need to do more replacements

**Comment by s-urbaniak** [comment]
hmm ... this is going to be a chicken/egg problem :thinking: as we use the example manifests in e2e tests, the image version is not available yet.

**Comment by s-urbaniak** [comment]
sorry, ignore me, i have to fix it.

**Review by paulfantom — APPROVED** [review]
:shipit:

**Pull request merged**
