### PR TITLE
*: update client-go and other dependencies

### PR DESCRIPTION
**Pull request by paulfantom**
Updating k8s dependencies to fully migrate to klog v2 (follow-up to https://github.com/brancz/kube-rbac-proxy/pull/92)

I had to swap `NewStaticCAContentFromFile` for more generic `NewStaticCAContent` as the former was removed in https://github.com/kubernetes/kubernetes/pull/88763

/cc @simonpasquier

### CODE REVIEW

**Comment by paulfantom** [comment]
I fixed issues reported by CI. This should be ready for review now.

**Comment by brancz** [comment]
Could you open an issue for a follow up to replace the `context.TODO()` calls?

**Comment by paulfantom** [comment]
@brancz done

**Comment by brancz** [comment]
Feel free to also grab #96 as a follow up :)

**Pull request merged**
