### PR TITLE
fix: use supported apiVersion for deployment and authorization

### LINKED ISSUE #151: Examples no longer work on k8s 1.22.0
Examples and Tests use deprecated `apiVersion` for `ClusterRole`  and `Deployment` and thus can't be `kubectl applied`

see e.g. https://kubernetes.io/docs/reference/using-api/deprecation-guide/#deployment-v116

### PR DESCRIPTION
**Pull request by sthaha**
From k8s version 1.22 the following apiVersions`[1][2]` are no longer served.
Hence the PR introduces the following changes
* replace `extensions/v1beta1` with `apps/v1`
* replace `authorization.k8s.io/v1beta1` with `authorization.k8s.io/v1`

`[1]`: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#tokenreview-v122
`[2]`: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#deployment-v116

Signed-off-by: Sunil Thaha <sthaha@redhat.com>

Fixes #151

### CODE REVIEW

**Comment by sthaha** [comment]
cc:  @paulfantom @jan--f @s-urbaniak  , could you please take a look?

**Comment by ibihim** [comment]
Why did you remove the READMEs?

**Comment by s-urbaniak** [comment]
@sthaha what @ibihim suggested is correct. please don't remove the examples.

**Comment by sthaha** [comment]
@s-urbaniak @ibihim I can submit a separate cleanup PR but since I have touched the examples, I thought I will clean up the duplicate `examples/non-resource-url/non-resource-url` as well which I think was added by mistake in 96d335949218c8630422d610b43cdb5fec547ce8  . 

In other words, after fixing the examples/non-resource-url/non-resource-url, and correcting the `kube-rbac-proxy version
to 0.11.0 in  examples/non-resource/non-resource-url, 

```bash
❯ diff examples/non-resource-url examples/non-resource-url/non-resource-url
```

```diff
Only in examples/non-resource-url: non-resource-url
diff examples/non-resource-url/README.md examples/non-resource-url/non-resource-url/README.md
5c5
< RBAC differentiates in two types, that need to be authorized, resources and non-resources. A resource request authorization, could for example be, that a requesting entity needs to be authorized to perform the `get` action on a particular Kubernetes Deployment. A non-resource authorization validates, that an entity is authorized to request a bare URL.
---
> RBAC differentiates in two types, that need to be authorized, resources and non-resoruces. A resource request authorization, could for example be, that a requesting entity needs to be authorized to perform the `get` action on a particular Kubernetes Deployment. A non-resource authorization validates, that an entity is authorized to request a bare URL.

```
which is a typo in `non-resoruces`

**Comment by ibihim** [comment]
@sthaha, I think it is amazing, that you continue to support the repository beyond the version bump, but could you add the 3 files back for this PR?

+73 -325 << 3 files get deleted: `examples/non-resource-url/non-resource-url/*`

**Comment by ibihim** [comment]
Ah, sorry. My bad. I completely misunderstood the reasoning. /lgtm

I actually was wondering about it the day before. :sweat_smile:

**Comment by s-urbaniak** [comment]
ah i see, now i also remember @jan--f talking about this :-) lgtm, let's ship

**Pull request merged**
