### PR TITLE
Add whitespace

### PR DESCRIPTION
**Pull request by ShazaAldawamneh**
this ticket to resolve issue: [(26) Add whitespace link](https://github.com/brancz/kube-rbac-proxy/issues/332)

### CODE REVIEW

**Comment by stlaz** [comment]
The commit says "Add whitespace link". What does the 'link' part mean?

**Comment by stlaz** [comment]
Please add signatures to your commits.

**Comment by ibihim** [comment]
The link was a link to Mo's comment. The initial issue was wrongly created and it stayed as is.

**Comment by ShazaAldawamneh** [comment]
it's my bad I know what Krzys meant because he explained the ticket when we have a meeting, and I forgot to ask him about the link word, will amend that and recommit with my signature @stlaz

**Pull request merged**
