### PR TITLE
chore: move --upstream-force-h2c out of --insecure-listen-address #139

### PR DESCRIPTION
**Pull request by andylibrian**
Upstream-force-h2c is a flag for upstream, while insecure-listen-address is for the proxy endpoint. Both can work
separately. One use case is having a secure terminating endpoint with kube-rbac-proxy while having an insecure upstream.

Signed-off-by: Andy Librian <andylibrian@gmail.com>

ref: #139

### CODE REVIEW

**Comment by s-urbaniak** [comment]
@andylibrian loooks great so far :+1: do you think it Is feasible to add an e2e test for this? Potentially we could contribute to https://github.com/brancz/prometheus-example-app to allow h2c requests.

**Comment by andylibrian** [comment]
I'm ok to that a test. This would be a new directory (something like `h2c-upstream`) along with existing `basics`, `tokenrequest`, etc. Sounds good to you?

**Comment by s-urbaniak** [comment]
@andylibrian that would be perfect, yes

**Comment by andylibrian** [comment]
@s-urbaniak I opened a PR in the example repo: https://github.com/brancz/prometheus-example-app/pull/11

Do you mind taking a look?

**Comment by brancz** [comment]
Pushed merged and pushed the new example app version

**Comment by s-urbaniak** [comment]
@brancz thank you! :pray: @andylibrian how do you feel finalizing this here? :)

**Comment by andylibrian** [comment]
Thanks @brancz!

@s-urbaniak, I'm still keen to add the test, hopefully next week

**Comment by s-urbaniak** [comment]
@andylibrian perfect, thank you and no rush! :pray:

**Comment by andylibrian** [comment]
@s-urbaniak I've added e2e test for h2c upstream. Do you mind taking a look?

**Comment by andylibrian** [comment]
The failing golint seems to be flakey:

```
run golangci-lint
  Running [/home/runner/golangci-lint-1.42.1-linux-amd64/golangci-lint run --out-format=github-actions] in [] ...
  level=error msg="Timeout exceeded: try increasing it by passing --timeout option"
```

Can we restart it?

**Comment by s-urbaniak** [comment]
@andylibrian i didn't do a thorough review yet, but do you mind fixing the linting issue first?

**Comment by andylibrian** [comment]
@s-urbaniak I ran `golangci-lint run` locally on this branch and it passed. I think the build was flaky. I was requesting to restart the build manually, but I went ahead with force pushing this branch hoping that it triggered another build.

**Comment by s-urbaniak** [comment]
@andylibrian thank you! We will have a look and I'll merge once e2e is green :+1:

**Comment by andylibrian** [comment]
@s-urbaniak Thank you for merging it!

**Pull request merged**
