### PR TITLE
Make image be rootless

### PR DESCRIPTION
**Pull request by camilamacedo86**
**Description**
- Make the docker image be rootless

**Motivation**
- https://github.com/kubernetes-sigs/kubebuilder/issues/1637
- Closes: https://github.com/brancz/kube-rbac-proxy/issues/84
- Following the good practices. See;  https://kubernetes.io/blog/2016/08/security-best-practices-kubernetes-deployment/

### CODE REVIEW

**Review by paulfantom — COMMENTED** [review]
Since this is removing the whole `vendor/` directory, could you also remove references to said directory from Makefile?

**Comment by paulfantom** [comment]
https://github.com/brancz/kube-rbac-proxy/pull/87 is merged now, could you rebase?

Thank you for this enhancement! :100:

**Comment by paulfantom** [comment]
It seems that an e2e test scenario using deployment files from https://github.com/brancz/kube-rbac-proxy/tree/master/test/e2e/allowpaths is failing in CI. 

Pod is failing to start due to:
> Error: container has runAsNonRoot and image has non-numeric user (nonroot), cannot verify user is non-root
> Error: container has runAsNonRoot and image will run as root

**Comment by camilamacedo86** [comment]
/hold
I need time to check it better, I will close the PR and re-open it with the final solution.

**Comment by paulfantom** [comment]
@camilamacedo86 Is there something left for this PR?

**Comment by camilamacedo86** [comment]
hi @paulfantom, 

Thank you for your support and patient. I want to look better on how we could update the manifests as well.  However, I need to stop to work on it. It is fine now and can get merged. Could you also to do. new release after this merge?

**Comment by harpratap** [comment]
@camilamacedo86 I tried this branch and I get this error - `Error: failed to start container "kube-rbac-proxy": Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "chdir to cwd (\"/home/nonroot\") set in config.json failed: permission denied": unknown` changing the user to 65532:65532 gives it permission to access home dir (https://github.com/GoogleContainerTools/distroless/blob/master/base/base.bzl#L7)

**Comment by camilamacedo86** [comment]
hi @harpratap, 

I am unable to reproduce the error. could you please let us know how are you doing this test?

**Comment by paulfantom** [comment]
@harpratap ping

**Comment by harpratap** [comment]
@camilamacedo86 I'm trying out with [this role & psp](https://gist.github.com/harpratap/9f1bb173f7725b42c950863e42e41fc9), forcing to user 65532 fixes it. But unfortunately not able to reproduce this on Kind or minikube yet. I have a suspicion that this is happening because of our use of containerd instead of docker

**Comment by camilamacedo86** [comment]
Hi @harpratap, 

Shows that the problem is because you are not using the changes made in the manifests. See: https://github.com/brancz/kube-rbac-proxy/pull/86/files#diff-c669d94f3867a7c8d5a54532c08e029bR61-R77. You came with this USER ID because of you check it out in https://github.com/GoogleContainerTools/distroless/blob/master/base/base.bzl#L7. But it is only a value for the const. We do not need to use this value to be able to use the distroless image.

**Comment by harpratap** [comment]
@camilamacedo86 I did try again after adding `spec.securityContext.runAsUser: 1001` and `spec.containers.allowPrivilegeEscalation: false` but still results in the same error

**Comment by harpratap** [comment]
This seems to be a known issue with distroless:nonroot with containerd. 
[This repo](https://github.com/michaelbannister/distroless-permissions-test) has a reproducible test and looks like there is some ongoing activity to fix it upstream - https://github.com/containerd/cri/pull/1397

It isn't related to this PR so this should be good to go, I'll watch for fixes in upstream. Thanks everyone!

**Comment by camilamacedo86** [comment]
Hi @harpratap, 

could we get it merged and do a release with it?

**Review by paulfantom — APPROVED** [review]
LGTM

**Review by metalmatze — APPROVED** [review]

**Comment by s-urbaniak** [comment]
LGTM too, thank you!

**Pull request merged**
