### PR TITLE
test/kubetest: add dumpLogs, increase job backoff, ensure kube-rbac-proxy deployment is gone

### LINKED ISSUE #108: Regression in Test/IgnorePath/WithIgnorePathNoMatch
We seem to fail consistently in FAIL: Test/IgnorePath/WithIgnorePathNoMatch, compare https://github.com/brancz/kube-rbac-proxy/runs/1790596451?check_suite_focus=true.

This seems to be introduced as part of https://github.com/brancz/kube-rbac-proxy/pull/104 but it might be a red herring as the e2e test there passed https://github.com/brancz/kube-rbac-proxy/runs/1569876652.

### PR DESCRIPTION
**Pull request by s-urbaniak**
This is a test to catch the flaky e2e failures.

Fixes #108

Signed-off-by: Sergiusz Urbaniak <sergiusz.urbaniak@gmail.com>

### CODE REVIEW

**Comment by s-urbaniak** [comment]
```
2021-03-30T12:21:14.8924424Z === RUN   Test/AllowPath/WithPathhNotAllowed
2021-03-30T12:21:53.8133487Z === LOGS default kube-rbac-proxy-client-h6h6n-2mlw9 kube-rbac-proxy-client
2021-03-30T12:21:53.8171196Z *   Trying 10.96.207.47...
2021-03-30T12:21:53.8171560Z * TCP_NODELAY set
2021-03-30T12:21:53.8172005Z * Connection timed out after 5000 milliseconds
2021-03-30T12:21:53.8172474Z * Closing connection 0
2021-03-30T12:21:53.8172907Z expecting 404 status code, got 000 instead
2021-03-30T12:21:53.8174472Z === LOGS default kube-rbac-proxy-client-h6h6n-2rsg7 kube-rbac-proxy-client
2021-03-30T12:21:53.8208795Z *   Trying 10.96.207.47...
2021-03-30T12:21:53.8209204Z * TCP_NODELAY set
2021-03-30T12:21:53.8209649Z * Connection timed out after 5000 milliseconds
2021-03-30T12:21:53.8210127Z * Closing connection 0
2021-03-30T12:21:53.8210562Z expecting 404 status code, got 000 instead
2021-03-30T12:21:53.8211675Z === LOGS default kube-rbac-proxy-client-h6h6n-9vq5r kube-rbac-proxy-client
2021-03-30T12:21:53.8246780Z *   Trying 10.96.207.47...
2021-03-30T12:21:53.8248156Z * TCP_NODELAY set
2021-03-30T12:21:53.8248619Z * Connection timed out after 5000 milliseconds
2021-03-30T12:21:53.8250178Z * Closing connection 0
2021-03-30T12:21:53.8250641Z expecting 404 status code, got 000 instead
2021-03-30T12:21:53.8251179Z     kubetest.go:125: checks failed: failed to run
2021-03-30T12:21:53.8381759Z === LOGS default kube-rbac-proxy-6877b45ccf-vj8rv kube-rbac-proxy
2021-03-30T12:21:53.8421552Z I0330 12:21:16.638699       1 main.go:190] Valid token audiences: 
2021-03-30T12:21:53.8422194Z I0330 12:21:16.638779       1 main.go:262] Generating self signed cert as no cert is provided
2021-03-30T12:21:53.8422915Z I0330 12:21:17.392112       1 main.go:312] Starting TCP socket on 0.0.0.0:8443
2021-03-30T12:21:53.8423422Z I0330 12:21:17.392515       1 main.go:319] Listening securely on 0.0.0.0:8443
2021-03-30T12:21:53.8424542Z === LOGS default kube-rbac-proxy-6877b45ccf-vj8rv prometheus-example-app
```

i need to dig deeper here, but this seems like some race in e2e test setup

**Comment by s-urbaniak** [comment]
OK, I rerun the e2e tests with this PR many times so I am somehow confident this will reduce the flakes (famous last words).

@brancz @metalmatze @jan--f @simonpasquier could one of you PTAL?

**Comment by simonpasquier** [comment]
lgtm, so it seems that waiting for the pods to be gone is what's fixing the flake?

**Comment by s-urbaniak** [comment]
> lgtm, so it seems that waiting for the pods to be gone is what's fixing the flake?
yes, plus a longer backoff setting (10 vs. 3) for request jobs.

**Pull request merged**
